import { createClient } from "@/lib/supabase/server";
import { ProductCreate } from "@/components/product-create";

interface VariantRow { id:string; sku:string; color:string|null; material:string|null; size:string|null; selling_price:number; quantity:number; minimum_quantity:number; }
interface ProductRow { id:string; name:string; slug:string; active:boolean; categories:{name:string}|null; product_variants:VariantRow[]; }

export default async function ProductsPage(){
 const supabase=await createClient();
 const [{data,error},{data:categories}]=await Promise.all([
  supabase.from("products").select("id,name,slug,active,categories(name),product_variants(id,sku,color,material,size,selling_price,quantity,minimum_quantity)").order("created_at",{ascending:false}).limit(100),
  supabase.from("categories").select("id,name").order("name")
 ]);
 const products=(data??[]) as unknown as ProductRow[];
 return <section className="animate-fade-in space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-sm font-medium text-[var(--gold)]">Каталог</p><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Товары</h1><p className="mt-2 text-sm text-[var(--muted)]">Управляй карточками, SKU и остатками в одном месте.</p></div><div className="rounded-full border border-[var(--line)] bg-[var(--card)] px-3 py-1.5 text-xs text-[var(--muted)]">{products.length} товаров</div></header>
 <ProductCreate categories={(categories??[]) as Array<{id:string;name:string}>}/>
 {error?<div className="rounded-2xl border border-[var(--line)] bg-[var(--card)] p-6 text-sm text-[var(--danger)]">Не удалось загрузить товары.</div>:products.length===0?<div className="rounded-2xl border border-dashed border-[var(--line)] bg-[var(--card)] p-10 text-center"><div className="mx-auto max-w-md"><div className="text-4xl">🧣</div><h2 className="mt-4 text-base font-semibold">Каталог пока пуст</h2><p className="mt-2 text-sm text-[var(--muted)]">Создай первый товар выше. После добавления он сразу появится здесь.</p></div></div>:<div className="grid gap-3">{products.map(product=>{const units=product.product_variants.reduce((sum,v)=>sum+v.quantity,0);const low=product.product_variants.filter(v=>v.quantity<=v.minimum_quantity).length;return <article key={product.id} className="rounded-2xl border border-[var(--line)] bg-[var(--card)] p-5 shadow-[0_8px_24px_rgba(31,26,20,0.035)] transition hover:shadow-[0_12px_30px_rgba(31,26,20,0.06)]"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><h2 className="truncate font-medium">{product.name}</h2><span className={`rounded-full px-2 py-1 text-[10px] font-medium ${product.active?"bg-[color:var(--background)]":"border border-[var(--line)] text-[var(--muted)]"}`}>{product.active?"Активен":"Черновик"}</span></div><p className="mt-1 text-xs text-[var(--muted)]">{product.categories?.name??"Без категории"} · {product.slug}</p></div><div className="grid grid-cols-3 gap-4 text-xs sm:grid-cols-4"><div><div className="text-[var(--muted)]">SKU</div><div className="mt-1 font-medium">{product.product_variants.length}</div></div><div><div className="text-[var(--muted)]">Остаток</div><div className="mt-1 font-medium">{units} шт.</div></div><div><div className="text-[var(--muted)]">Дефицит</div><div className="mt-1 font-medium">{low}</div></div><div className="hidden sm:block"><div className="text-[var(--muted)]">Цена от</div><div className="mt-1 font-medium">{product.product_variants.length?Math.min(...product.product_variants.map(v=>Number(v.selling_price))).toLocaleString("ru-RU"):"—"} TJS</div></div></div></div></article>})}</div>}
 </section>;
}
