import { createClient } from "@/lib/supabase/server";
import { ProductCreate } from "@/components/product-create";

interface VariantRow { id:string; sku:string; color:string|null; material:string|null; size:string|null; selling_price:number; quantity:number; minimum_quantity:number; }
interface ProductRow { id:string; name:string; slug:string; active:boolean; categories:{name:string}|null; product_variants:VariantRow[]; }

export default async function ProductsPage(){
 const supabase=await createClient();
 const [{data,error},{data:categories}]=await Promise.all([
  supabase.from("products").select("id,name,slug,active,categories(name),product_variants(id,sku,color,material,size,selling_price,quantity,minimum_quantity)").order("created_at",{ascending:false}).limit(100),
  supabase.from("categories").select("id,name").order("name")
 ]);
 const products=(data??[]) as unknown as ProductRow[];
 return <section className="animate-fade-in space-y-5 sm:space-y-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1.5 text-sm font-medium text-[var(--gold)]">Каталог</p><h1 className="text-[30px] font-semibold tracking-tight sm:text-4xl">Товары</h1><p className="mt-2 max-w-2xl text-sm leading-5 text-[var(--muted)]">Карточки, SKU и остатки — в одном месте.</p></div><div className="w-fit rounded-full border border-[var(--line)] bg-[var(--card)] px-3 py-1.5 text-xs text-[var(--muted)]">{products.length} товаров</div></header>
 <ProductCreate categories={(categories??[]) as Array<{id:string;name:string}>}/>
 {error?<div className="rounded-2xl border border-[var(--line)] bg-[var(--card)] p-5 text-sm text-[var(--danger)]">Не удалось загрузить товары.</div>:products.length===0?<div className="rounded-2xl border border-dashed border-[var(--line)] bg-[var(--card)] p-8 text-center sm:p-10"><div className="mx-auto max-w-md"><div className="text-4xl">🧣</div><h2 className="mt-4 text-base font-semibold">Каталог пока пуст</h2><p className="mt-2 text-sm leading-5 text-[var(--muted)]">Создай первый товар — он появится здесь автоматически.</p></div></div>:<div className="grid gap-3">{products.map(product=>{const units=product.product_variants.reduce((sum,v)=>sum+v.quantity,0);const low=product.product_variants.filter(v=>v.quantity<=v.minimum_quantity).length;return <article key={product.id} className="rounded-2xl border border-[var(--line)] bg-[var(--card)] p-4 shadow-[0_8px_24px_rgba(31,26,20,0.035)] transition hover:shadow-[0_12px_30px_rgba(31,26,20,0.06)] sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="max-w-full truncate font-medium">{product.name}</h2><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-medium ${product.active?"bg-[color:var(--background)]":"border border-[var(--line)] text-[var(--muted)]"}`}>{product.active?"Активен":"Черновик"}</span></div><p className="mt-1 truncate text-xs text-[var(--muted)]">{product.categories?.name??"Без категории"} · {product.slug}</p></div><div className="grid grid-cols-3 gap-2 border-t border-[var(--line)] pt-3 text-xs sm:grid-cols-4 sm:gap-4 sm:border-0 sm:pt-0"><div><div className="text-[var(--muted)]">SKU</div><div className="mt-1 font-medium">{product.product_variants.length}</div></div><div><div className="text-[var(--muted)]">Остаток</div><div className="mt-1 font-medium">{units} шт.</div></div><div><div className="text-[var(--muted)]">Дефицит</div><div className="mt-1 font-medium">{low}</div></div><div className="hidden sm:block"><div className="text-[var(--muted)]">Цена от</div><div className="mt-1 font-medium">{product.product_variants.length?Math.min(...product.product_variants.map(v=>Number(v.selling_price))).toLocaleString("ru-RU"):"—"} TJS</div></div></div></div></article>})}</div>}
 </section>;
}
