"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
interface Category{ id:string; name:string }
export function ProductCreate({categories}:{categories:Category[]}){
 const router=useRouter();const [form,setForm]=useState({name:"",slug:"",category_id:"",sku:"",color:"",material:"",size:"",cost_price:"",selling_price:"",quantity:"0",minimum_quantity:"0",description:""});const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const set=(key:keyof typeof form,value:string)=>setForm(v=>({...v,[key]:value}));
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:form.name,slug:form.slug,category_id:form.category_id||null,description:form.description||undefined,variant:{sku:form.sku,color:form.color||undefined,material:form.material||undefined,size:form.size||undefined,cost_price:Number(form.cost_price),selling_price:Number(form.selling_price),quantity:Number(form.quantity),minimum_quantity:Number(form.minimum_quantity)}})});const d=await r.json();if(!r.ok)throw new Error(d.error??"Could not create product");setForm({name:"",slug:"",category_id:"",sku:"",color:"",material:"",size:"",cost_price:"",selling_price:"",quantity:"0",minimum_quantity:"0",description:""});router.refresh()}catch(e){setError(e instanceof Error?e.message:"Could not create product")}finally{setBusy(false)}}
 const input=(label:string,key:keyof typeof form,type="text",required=false)=><label className="block text-xs font-medium text-[var(--muted)]">{label}<input required={required} type={type} value={form[key]} onChange={e=>set(key,e.target.value)} className="mt-1.5 w-full rounded-xl border border-[var(--line)] bg-transparent px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-black/10"/></label>;
 return <form onSubmit={submit} className="rounded-2xl border border-[var(--line)] bg-[var(--card)] p-5"><div className="mb-4"><h2 className="font-medium">Add product</h2><p className="mt-1 text-xs text-[var(--muted)]">Create a product and its first SKU.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{input("Product name","name","text",true)}{input("Slug","slug","text",true)}<label className="block text-xs font-medium text-[var(--muted)]">Category<select value={form.category_id} onChange={e=>set("category_id",e.target.value)} className="mt-1.5 w-full rounded-xl border border-[var(--line)] bg-transparent px-3 py-2.5 text-sm outline-none"><option value="">Uncategorized</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{input("SKU","sku","text",true)}{input("Color","color")}{input("Material","material")}{input("Size","size")}{input("Cost price","cost_price","number",true)}{input("Selling price","selling_price","number",true)}{input("Quantity","quantity","number",true)}{input("Minimum quantity","minimum_quantity","number",true)}</div><label className="mt-3 block text-xs font-medium text-[var(--muted)]">Description<textarea value={form.description} onChange={e=>set("description",e.target.value)} className="mt-1.5 min-h-24 w-full rounded-xl border border-[var(--line)] bg-transparent px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-black/10"/></label>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="mt-4 rounded-xl bg-[#1f1a14] px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{busy?"Creating…":"Add product"}</button></form>;
}
