"use client";
import { useState } from "react";

export default function AIStudioPage(){
 const [file,setFile]=useState<File|null>(null);const [category,setCategory]=useState("hijabs");const [material,setMaterial]=useState("");const [color,setColor]=useState("");const [size,setSize]=useState("");const [price,setPrice]=useState("");const [result,setResult]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 async function generate(){
  if(!file)return; if(file.size>5*1024*1024){setError("Image exceeds 5 MB");return;} setLoading(true);setError("");setResult("");
  try{
   const form=new FormData();form.append("file",file);const upload=await fetch("/api/uploads/product-image",{method:"POST",body:form});const uploaded=await upload.json();if(!upload.ok)throw new Error(uploaded.error??"Upload failed");
   const imageBase64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(",")[1]??"");r.onerror=()=>reject(new Error("Could not read image"));r.readAsDataURL(file);});
   const res=await fetch("/api/ai/product-card",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({imageBase64,sourceImagePath:uploaded.path,mimeType:file.type,category,material:material||undefined,color:color||undefined,size:size||undefined,price:price?Number(price):undefined})});const data=await res.json();if(!res.ok)throw new Error(data.error??"Generation failed");setResult(JSON.stringify(data,null,2));
  }catch(e){setError(e instanceof Error?e.message:"Generation failed")}finally{setLoading(false)}
 }
 return <section><header className="mb-8"><p className="mb-2 text-sm text-[var(--gold)]">AI Studio</p><h1 className="text-3xl font-semibold tracking-tight">Product card generator</h1><p className="mt-2 text-sm text-[var(--muted)]">The original image is stored separately before AI generation. Output is schema-validated and remains a draft until approved.</p></header><div className="grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="rounded-2xl border border-[var(--line)] bg-[var(--card)] p-6"><label className="block text-sm font-medium">Image<input className="mt-2 block w-full text-sm" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><div className="mt-5 grid gap-3 sm:grid-cols-2"><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Category" className="rounded-xl border border-[var(--line)] bg-transparent px-3 py-2"/><input value={material} onChange={e=>setMaterial(e.target.value)} placeholder="Material" className="rounded-xl border border-[var(--line)] bg-transparent px-3 py-2"/><input value={color} onChange={e=>setColor(e.target.value)} placeholder="Color" className="rounded-xl border border-[var(--line)] bg-transparent px-3 py-2"/><input value={size} onChange={e=>setSize(e.target.value)} placeholder="Size" className="rounded-xl border border-[var(--line)] bg-transparent px-3 py-2"/><input value={price} onChange={e=>setPrice(e.target.value)} inputMode="decimal" placeholder="Price" className="rounded-xl border border-[var(--line)] bg-transparent px-3 py-2 sm:col-span-2"/></div><button disabled={!file||loading} onClick={generate} className="mt-5 w-full rounded-xl bg-[#1f1a14] px-4 py-3 text-sm font-medium text-white disabled:opacity-50">{loading?"Uploading & generating…":"Generate product card"}</button>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</div><div className="min-h-64 rounded-2xl border border-[var(--line)] bg-[#1f1a14] p-6 text-sm text-white"><div className="mb-3 text-white/60">Structured output preview</div><pre className="max-h-[520px] overflow-auto whitespace-pre-wrap text-xs leading-5">{result||"Your validated AI output will appear here."}</pre></div></div></section>;
}